server:
  port: 8080
  shutdown: graceful
  error:
    whitelabel:
      enabled: true
spring:
  application:
    name: portfolio-be
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
  devtools:
    restart:
      enabled: false
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    supported-submit-methods: []
    tags-sorter: alpha
    operations-sorter: method
    groups-order: ASC
decorator:
  datasource:
    p6spy:
      enable-logging: true