spring:
  datasource:
    # jdbc:mysql://localhost:3306/portfolio? -> 뒤 부터는 제거
    url: ENC(1+D+bUX+XPm3NvR9xsAIPSlxBwNQsrTwGedm+qeJC8Riy82Az/JlO7rkSV8uimTJFkTmZLYLj2uJpP/m1MNvE/ojAqUjef2OngrcMAcf9uNK4qm2q67bcS7VU8FF9c//imECXE5JsnyzHrY2zAnBgsBz5Di44PZ8hZ/vnI/N8GeqHUO5XZIkIqrEJhXn5c3j)
    username: ENC(LJC/uBe6NdTlhJIVoCOflQ==)
    password: ENC(Hvy08IN0YruPhhyG3haSZA==)
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ENC(DGY0Aisb4a1gWKfGWQ1RWnRjn8VCBQXa)
      port: 6379
# JWT
# 60000 = 1m

jwt:
  secret:
    key: ENC(SyElIxoBnMHO1Yky5usxIEVPnclOEAaKjJU7CMOfVtm9MGNEW7rLcp7FNUF8xTtb)
  access:
    expire: 10800000 # 1 Hour
  refresh:
    expire: 86400000 # 1 Day